version: '3.7'

services:

  ng:
    build: ./ng
    restart: always
    ports:
      - "4200:4200"
    networks:
      - ng-ab-network

  api:
    build: ./api
    restart: on-failure
    ports:
      - "3000:3000"
    env_file: ./api/api.env
    networks:
      - ng-ab-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
        - "3636:3306"
    env_file: ./db/db.env
    networks:
      - ng-ab-network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - ng-ab-network

  orm:
    build: ./orm
    restart: always
    depends_on:
      - db
    networks:
      - ng-ab-network


networks:
  ng-ab-network:
    name: ng-ab-network
