version: '3.7'

services:
  node:
    build: ./node
    restart: on-failure
    ports:
      - "3794:3000"
    env_file: ./node/node.env
    # volumes:
    #   - .node/api:/usr/src/app
    # networks:
    #   - ng-ab-network
  # sql:
  #   build: ./sql
  #   restart: on-failure
  #   ports:
  #     - "3306:3306"
  #   env_file: ./sql/sql.env
    # networks:
    #   - ng-ab-network

# networks:
#   ng-ad:
#     name: ng-ab-network
