version: '3.7'

services:

  node:
    build: ./node
    restart: on-failure
    ports:
      - "1000:3000"
    env_file: ./node/node.env
    # volumes:
    #   - ./node/api:/usr/src/app
    networks:
      - ng-ab-network

  sql:
    build: ./sql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
        - "1001:3306"
    env_file: ./sql/sql.env
    networks:
      - ng-ab-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 1002:8080
    networks:
      - ng-ab-network


networks:
  ng-ab-network:
    name: ng-ab-network
